# Generated by Django 2.1.1 on 2018-09-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='t_user',
        ),
    ]
