# Generated by Django 2.1.1 on 2018-09-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180905_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
    ]
